import type { User, Course, Enrollment, Lesson, CourseMaterial, DiscussionMessage } from '@/types';

// Demo admin user
export const mockUsers: User[] = [
  {
    id: 1,
    email: 'admin@learnthru.com',
    name: 'Admin User',
    role: 'admin',
    avatar_url: null,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
  {
    id: 2,
    email: 'stella@learnthru.com',
    name: 'Stella Walton',
    role: 'student',
    avatar_url: null,
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-01-15'),
  },
  {
    id: 3,
    email: 'instructor@learnthru.com',
    name: 'Bernard Carr',
    role: 'instructor',
    avatar_url: null,
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-10'),
  },
  {
    id: 4,
    email: 'henry@learnthru.com',
    name: 'Henry Poole',
    role: 'instructor',
    avatar_url: null,
    created_at: new Date('2024-01-12'),
    updated_at: new Date('2024-01-12'),
  },
  {
    id: 5,
    email: 'helena@learnthru.com',
    name: 'Helena Lowe',
    role: 'student',
    avatar_url: null,
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-01'),
  },
];

export const mockCourses: Course[] = [
  {
    id: 1,
    title: 'English - UNIT III',
    description: 'Advanced English grammar and composition for upper elementary students.',
    instructor_id: 3,
    instructor_name: 'Leona Jimenez',
    category: 'Language Arts',
    level: 'Upper Elementary',
    thumbnail_url: null,
    status: 'published',
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
  {
    id: 2,
    title: 'English - UNIT II',
    description: 'Intermediate English reading and writing skills.',
    instructor_id: 4,
    instructor_name: 'Cole Chandler',
    category: 'Language Arts',
    level: 'Lower Elementary',
    thumbnail_url: null,
    status: 'published',
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-01-05'),
  },
  {
    id: 3,
    title: 'French Speaking Classes',
    description: 'New French speaking classes are available. Etudier en France for B1 and B2 levels.',
    instructor_id: 4,
    instructor_name: 'Cole Chandler',
    category: 'Language',
    level: 'Primary',
    thumbnail_url: null,
    status: 'published',
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-10'),
  },
  {
    id: 4,
    title: 'Mathematics - Practical Life',
    description: 'Montessori practical life mathematics activities.',
    instructor_id: 3,
    instructor_name: 'Bernard Carr',
    category: 'Mathematics',
    level: 'Primary',
    thumbnail_url: null,
    status: 'published',
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-01'),
  },
  {
    id: 5,
    title: 'Sensorial Activities',
    description: 'Montessori sensorial materials and activities curriculum.',
    instructor_id: 4,
    instructor_name: 'Henry Poole',
    category: 'Sensorial',
    level: 'Primary',
    thumbnail_url: null,
    status: 'draft',
    created_at: new Date('2024-02-15'),
    updated_at: new Date('2024-02-15'),
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: 1,
    user_id: 2,
    course_id: 1,
    status: 'active',
    progress: 65,
    enrolled_at: new Date('2024-01-20'),
    completed_at: null,
  },
  {
    id: 2,
    user_id: 2,
    course_id: 2,
    status: 'active',
    progress: 40,
    enrolled_at: new Date('2024-01-22'),
    completed_at: null,
  },
  {
    id: 3,
    user_id: 2,
    course_id: 3,
    status: 'active',
    progress: 20,
    enrolled_at: new Date('2024-02-01'),
    completed_at: null,
  },
  {
    id: 4,
    user_id: 5,
    course_id: 1,
    status: 'active',
    progress: 80,
    enrolled_at: new Date('2024-01-25'),
    completed_at: null,
  },
  {
    id: 5,
    user_id: 5,
    course_id: 4,
    status: 'completed',
    progress: 100,
    enrolled_at: new Date('2024-02-01'),
    completed_at: new Date('2024-03-01'),
  },
];

export const mockLessons: Lesson[] = [
  {
    id: 1,
    course_id: 1,
    title: 'Introduction to Grammar',
    content: 'Basic grammar concepts and rules.',
    order_index: 1,
    duration_minutes: 45,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
  },
  {
    id: 2,
    course_id: 1,
    title: 'Sentence Structure',
    content: 'Understanding sentence components.',
    order_index: 2,
    duration_minutes: 50,
    created_at: new Date('2024-01-02'),
    updated_at: new Date('2024-01-02'),
  },
  {
    id: 3,
    course_id: 2,
    title: 'Reading Comprehension',
    content: 'Strategies for understanding texts.',
    order_index: 1,
    duration_minutes: 40,
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-01-05'),
  },
  {
    id: 4,
    course_id: 3,
    title: 'French Pronunciation',
    content: 'Basic French sounds and phonetics.',
    order_index: 1,
    duration_minutes: 30,
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-10'),
  },
];

export const mockCourseMaterials: CourseMaterial[] = [
  {
    id: 1,
    course_id: 1,
    title: 'Grammar Basics - Chapter 1',
    type: 'document',
    url: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/img/table-word.jpg',
    content: null,
    sort_order: 1,
    created_at: new Date('2024-03-15'),
    uploaded_by: 3,
    is_active: true,
    uploader_name: 'Bernard Carr',
  },
  {
    id: 2,
    course_id: 1,
    title: 'Introduction to English Grammar',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    content: null,
    sort_order: 2,
    created_at: new Date('2024-03-16'),
    uploaded_by: 3,
    is_active: true,
    uploader_name: 'Bernard Carr',
  },
  {
    id: 3,
    course_id: 2,
    title: 'Reading Comprehension Exercises',
    type: 'document',
    url: 'https://www.africau.edu/images/default/sample.pdf',
    content: null,
    sort_order: 1,
    created_at: new Date('2024-03-17'),
    uploaded_by: 4,
    is_active: true,
    uploader_name: 'Henry Poole',
  },
  {
    id: 4,
    course_id: 3,
    title: 'French Pronunciation Guide',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=K4DyBUG242c',
    content: null,
    sort_order: 1,
    created_at: new Date('2024-03-18'),
    uploaded_by: 4,
    is_active: true,
    uploader_name: 'Henry Poole',
  },
  {
    id: 5,
    course_id: 4,
    title: 'Math Worksheet - Addition',
    type: 'document',
    url: 'https://www.africau.edu/images/default/sample.pdf',
    content: null,
    sort_order: 1,
    created_at: new Date('2024-03-19'),
    uploaded_by: 3,
    is_active: true,
    uploader_name: 'Bernard Carr',
  },
];

export const mockDiscussionMessages: DiscussionMessage[] = [
  {
    id: 1,
    course_id: 1,
    user_id: 3,
    message: 'Welcome to the English Unit III discussion! Feel free to ask any questions about the course material.',
    is_flagged: false,
    is_deleted: false,
    created_at: new Date('2024-03-15T10:00:00'),
    user_name: 'Bernard Carr',
    user_avatar: null,
    user_role: 'instructor',
  },
  {
    id: 2,
    course_id: 1,
    user_id: 2,
    message: 'Thank you! I had a question about the grammar exercises in Chapter 1.',
    is_flagged: false,
    is_deleted: false,
    created_at: new Date('2024-03-15T10:30:00'),
    user_name: 'Stella Walton',
    user_avatar: null,
    user_role: 'student',
  },
  {
    id: 3,
    course_id: 1,
    user_id: 5,
    message: 'I found the video explanation really helpful!',
    is_flagged: false,
    is_deleted: false,
    created_at: new Date('2024-03-15T11:00:00'),
    user_name: 'Helena Lowe',
    user_avatar: null,
    user_role: 'student',
  },
  {
    id: 4,
    course_id: 1,
    user_id: 3,
    message: 'Great to hear! Let me know if you need any clarification on the upcoming assignments.',
    is_flagged: false,
    is_deleted: false,
    created_at: new Date('2024-03-15T11:15:00'),
    user_name: 'Bernard Carr',
    user_avatar: null,
    user_role: 'instructor',
  },
];

// Demo credentials
export const DEMO_CREDENTIALS = {
  admin: { email: 'admin@learnthru.com', password: 'admin123' },
  student: { email: 'stella@learnthru.com', password: 'student123' },
  instructor: { email: 'instructor@learnthru.com', password: 'instructor123' },
};

// Check if using mock data (no database connected)
export const USE_MOCK_DATA = false;
